global:
  resolve_timeout: 5s

route:
  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first
  # notification.
  group_wait: 5s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 5s

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 5s

  # A default receiver
  receiver: webhook_receiver
receivers:
  - name: webhook_receiver
    webhook_configs:
      - url: http://api:8000/api/v2/alerts
        send_resolved: false
